### ISSUE TITLE
Initialize Terraform step fails

### ISSUE THREAD

**Issue by simonaco** [microsoft/NubesGen#100]
1. In your Git repository, run curl command curl "https://nubesgen.com/demo.tgz?region=eastus&application=APP_SERVICE.free&runtime=DOCKER&database=NONE.free&gitops=true" | tar -xzvf -
2. Run script: bash -c "$(curl -fsSL https://nubesgen.com/gitops/setup.sh)" 
3. Continue with steps
Notice Terraform initialization failing.

**Comment by jdubois** [comment]
@cmaneu I think you had the solution to this, it was a subscription issue, is it?

**Comment by ernani** [comment]
This seems to be an RBAC issue with the service principal inside the tenant that owns that subscription. Make sure to create the service principal to the same tenant the sub is within and let us know if that works.
