### ISSUE TITLE
Improve TF State Storage account 

### ISSUE THREAD

**Issue by cmaneu** [microsoft/NubesGen#110]
We use an Azure Storage account to store the Terraform state. This storage account is created by the shell script.

We should provide a way to manage this with Terraform instead. We can take inspiration from [CAF Landing zone](https://github.com/Azure/caf-terraform-landingzones/blob/master/caf_launchpad/main.tf), where if I'm not mistaken, this is done: 
- Apply a basic terraform template, with state in local, containing the storage account
- Push the TF state to the storage account

## Implementation details
- To do this, we need a "fork" in our CI/CI script and/or documentation. 
- How we do this in a smart way? Querying the rg to see if the resource group is present? Using a secret (can a github action change a secret value? Querying the "remote TF state" (can we do that?)

**Comment by jdubois** [comment]
+1 on this, we definitely need to improve/clarify that part. Also we need a clean way to suppress the storage account when the person wants to delete everything.
One of the good ideas I've seen in this forum is also to tag the storage account with the name of the project, so it's easier to understand which storage account manages which project.

**Comment by jdubois** [comment]
The storage account is now tagged in the project, so that's easier to do.
