### ISSUE TITLE
Output the resource group name

### ISSUE THREAD

**Issue by agoncal** [microsoft/NubesGen#114]
##### **Overview of the issue**

Resource groups are important in Azure as you can mange resources (app, db). It would be nice to display the name of the group once Terraform has applied its templates. At the moment, only the `application_hostname` is displayed:

```
module.application.azurerm_app_service.application: Creation complete after 42s [id=/subscriptions/938928af-1e32-4226-b619-fd898a1cd7da/resourceGroups/rg-demo-2882-0286-9283-1371-dev-001/providers/Microsoft.Web/sites/app-demo-2882-0286-9283-1371-dev-001]

Apply complete! Resources: 7 added, 0 changed, 0 destroyed.

Outputs:

application_hostname = "https://app-demo-2882-0286-9283-1371-dev-001.azurewebsites.net"
```

It would be nice to have the resource group name as well:

```
Outputs:

application_hostname = "https://app-demo-2882-0286-9283-1371-dev-001.azurewebsites.net"
resource_group = "rg-demo-2882-0286-9283-1371-dev-001"
```

##### **Motivation for or Use Case**

Even if the resource group name can be easily found in the logs, it would be nice to have it directly in the output so then we can use `az group` commands (eg. `az group show --resource-group rg-demo-2882-0286-9283-1371-dev-001`).

##### **Suggest a Fix**

In the `outputs.tf` we should have something like that (the following works, but I'm not totally sure of the syntax as I don't know much about Terraform)

```
output "resource_group" {
    value       = local.resource_group
    description = "The resource group."
}
```

##### **NubesGen Version(s)**

NubesGen v0.1.0

##### **Browsers and Operating System**

MacOSX and Chrome

**Comment by jdubois** [comment]
Yes, let's do it, this should be easy, and useful for end-users.

**Comment by jdubois** [comment]
Closing as #130 is merged, thanks @agoncal !
