### ISSUE TITLE
Feature: Prettier Java for formatting Java code

### ISSUE THREAD

**Issue by pascalgrimaud** [microsoft/NubesGen#132]
##### **Overview of the issue**

I'm suggesting to add prettier-java https://github.com/jhipster/prettier-java for formatting all Java code.
What do you think ?

cc @jdubois as you know well this project :-)

##### **Motivation for or Use Case**

Consistency in existing code

##### **Suggest a Fix**

- add prettier-java in package.json dependencies
- add pre commit hook
- format all existing Java code

##### **NubesGen Version(s)**

current main

**Comment by jdubois** [comment]
Oh @pascalgrimaud it's soon going to be called the "Julien stack", with all my projects using eache other 🤣
Yes let's do it, but be careful as we have already a package.json from @cmaneu and I have no idea how it works

**Comment by pascalgrimaud** [comment]
I don't see any package json at root folder.
Anyway, if it's accepted, I can take care of it

**Comment by cmaneu** [comment]
Yes, the new front will need some dev tools (compiling TypeScript and some CSS compilation as well). But all the front is in a specific folder and not at the root folder.
