### ISSUE TITLE
Logging is not enabled for this container

### ISSUE THREAD

**Issue by agoncal** [microsoft/NubesGen#140]
##### **Overview of the issue**

I am trying to adapt NubesGen to deploy a Quarkus application. It doesn't work and I can't see the logs to diagnose what's wrong. I have installed Application Insights, can stream the logs, but no logs about the application.

##### **Reproduce the error**

I'm using NubesGen 0.1.1 with Application Insights and GitHub actions. When I push my code, everything works fine and the application gets deployed at https://app-demo-5412-0427-6050-1036-devq-001.azurewebsites.net. Good. But when I click on the link, I get:

```
:( Application Error
If you are the application administrator, you can access the diagnostic resources.
```

When I click on the link to diagnose the app, I get `Web App Down` and when I browse the logs I see:

```
INFO  - Starting container for site
INFO  - docker run -d -p 4732:80 --name app-demo-5412-0427-6050-1036-devq-001_0_2e3ff278 -e WEBSITES_ENABLE_APP_SERVICE_STORAGE=false -e WEBSITE_SITE_NAME=app-demo-5412-0427-6050-1036-devq-001 -e WEBSITE_AUTH_ENABLED=False -e WEBSITE_ROLE_INSTANCE_ID=0 -e WEBSITE_HOSTNAME=app-demo-5412-0427-6050-1036-devq-001.azurewebsites.net -e WEBSITE_INSTANCE_ID=ff658300eddad1c3f077dd4a34ab735ddc289731a761d2fed0aed11557821f2c mcr.microsoft.com/azure-app-service/java:11-java11_200714234736

INFO  - Logging is not enabled for this container.Please use https://aka.ms/linux-diagnostics to enable logging to see container logs here.

INFO  - Initiating warmup request to container app-demo-5412-0427-6050-1036-devq-001_0_2e3ff278 for site app-demo-5412-0427-6050-1036-devq-001
ERROR - Container app-demo-5412-0427-6050-1036-devq-001_0_2e3ff278 for site app-demo-5412-0427-6050-1036-devq-001 has exited, failing site start2021-06-03T11:21:39.914Z ERROR - Container app-demo-5412-0427-6050-1036-devq-001_0_2e3ff278 didn't respond to HTTP pings on port: 80, failing site start. See container logs for debugging.
INFO  - Stopping site app-demo-5412-0427-6050-1036-devq-001 because it failed during startup.
```

And when I visit the https://aka.ms/linux-diagnostics page it tells me to check logs streams which tells me that logs are not enabled.

Any idea on how I can see the logs of my app ?

##### **NubesGen Version(s)**

0.1.1

##### **Browsers and Operating System**

MacOSX + Chrome

**Comment by jdubois** [comment]
Do you run application as a Docker image or as a Java application? The issue with Docker images is that you won't have the Java agent installed automatically (so monitoring won't be great), and logging will be very limited

**Comment by agoncal** [comment]
I'm basing my work on _Spring Book (Java) with Maven_, that's why I found it strange to see a `docker run` command. It generated the templates using the following command, and then changed them so it fits to Quarkus:

```shell
curl "https://nubesgen.com/demo.tgz?region=francecentral&application=APP_SERVICE.free&runtime=SPRING&database=MYSQL.basic&addons=application_insights&gitops=true" | tar -xzvf -
```

**Comment by jdubois** [comment]
OK then it's Java. You're seeing Docker in the logs as internally this is running inside a Docker container, but this shouldn't be your issue. Let me test.

**Comment by jdubois** [comment]
I could deploy my app and see the logs, maybe it's because of the way Quarkus handles logging? I'll ping you in parallel, let's do some pair debugging

**Comment by agoncal** [comment]
Hum. I might be doing something wrong because I took your example (the JHipster Sample App), deployed it, and got the exact same problem.

**Comment by jdubois** [comment]
Closing as we fixed together in 1:1
One of the issues is that we don't have logging enabled by default - but that cost money to add Log Analytics, so we need to decide whether it's a good idea or not (it's good practice to add logging, monitoring, etc, but all those add up at some point)

**Comment by jdubois** [comment]
And this is documented in #142 - thanks @agoncal !!
