### ISSUE TITLE
Create documentation website

### ISSUE THREAD

**Issue by cmaneu** [microsoft/NubesGen#178]
##### **Overview of the issue**

As any OpenSource project, we need to have a great documentation. We already have some [docs here](https://github.com/microsoft/NubesGen/tree/main/docs).

##### **Motivation for or Use Case**

We would like to have a proper documentation website. Exact content is TBD (ideas welcome!) but here are some ideas we had: 

- Porting over the existing docs
- Having better _getting started_ documentations
- Have a FAQ for "next steps" (eg.: I've deployed my website, how do I add a custom domain now?)
- Use docs as a "poor MVP" (eg: we're wondering if Azure DevOps builds should be supported. Add a documentation page for this, and measure with Clarity if we have any traction to that doc page)
- Have a "Contributing" space for better instructions for contributors.

##### **What to build?**

I was thinking about a [VuePress](https://vuepress.vuejs.org/) website, stored under `/docs` folder, and hosted in GitHub pages, but **this is not mandatory!**. Happy to have a conversation about it :)

**After discussions and @stevengonsalvez PR**
We'll build that V2 of the documentation with docsify.

- [x] Import @stevengonsalvez work on `docs-v2` branch
- [ ] Revamp design & logos
- [ ] Add appropriate plugins
   - [x] [Edit on GitHub](https://github.com/njleonzhang/docsify-edit-on-github)
   - [x] [Tabbed content](https://jhildenbiddle.github.io/docsify-tabs), useful to show different usages (Web app, UI) or different IaC tools (bicep, terraform)
   - [ ] [Flexible Alerts](https://github.com/fzankl/docsify-plugin-flexible-alerts)
   - [ ] This [Example panels](https://vagnerdomingues.github.io/docsify-example-panels/#/) Plugin could be quite interesting
   - [ ] Look for a syntax highlighting plugin
- [ ] Create basic Documentation structure (What is NubesGen? Getting started, Core concepts, Cookbooks, Contributing)

**Comment by jdubois** [comment]
Thanks @stevengonsalvez but we have a limitation: it must not be hosted on a third-party website. This is still done by Microsoft, we can't have advertisements, third-party trackers, etc.

**Comment by stevengonsalvez** [comment]
docsify is just a vue based static site generator ... not hosted site. 

eg: made this from a fork - https://github.com/stevengonsalvez/Nubesgen/tree/feature/docsify

Hosted on github pages - https://stevengonsalvez.github.io/NubesGen/#/

>just a draft

**Comment by jdubois** [comment]
Oh that website is crazy good!!!!! And yes that would work!
I'm voting for this, @cmaneu WDYT?

**Comment by cmaneu** [comment]
Hey @stevengonsalvez,
Thanks for your example! I've forgotten about docsify.
I like what I see 😄. The only caveat/question I have is about the navigation.
Do you know if it's possible to create "sections"? It's a concept we have in docusaurus/vuepress. I think this is something we will need quite quickly: 
- A Docs section with getting started, gitops setup, etc...
- A reference: for the CLI, for the API, ...
- Maybe other sections like:  releases, learn, ...

Another requirement that we will have is code highlighting, ideally that supports bash, terraform, bicep (!) and yaml (GitHub actions). 

@stevengonsalvez do you know if these requirements can be met with docsify? (seems way simpler than docusaurus to setup)

**Comment by stevengonsalvez** [comment]
Everything to do with Sections is with just how you link up the Sidebar (and probably even the Navbar) - which is a md file with references
Standard markdown code highlighting (so think whatever is  standard md ). things like plantuml, mermaid have some plugins that I've seen to render.

Used docusaurus as well - Unless heavy customisation is needed, docsify seemed to give all that is needed. But then again , the everything is md . Could easily switch to docusaurus with the same structure as you could just define layouts.

**Comment by cmaneu** [comment]
Closed by #289
