### ISSUE TITLE
NubesGen generated project not working on Mac ARM64

### ISSUE THREAD

**Issue by iemejia** [microsoft/NubesGen#198]
##### **Overview of the issue**

NubesGen generated projects do not work on new Macs because the aztfmod/azurecaf provider does not support yet ARM64

##### **Reproduce the error**

Generate a nubesgen project from the web UI and try to run terraform init on a Mac M1

```
 % terraform init
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/azurerm versions matching ">= 2.75.0"...
- Finding aztfmod/azurecaf versions matching "1.2.8"...
- Installing hashicorp/azurerm v2.86.0...
- Installed hashicorp/azurerm v2.86.0 (signed by HashiCorp)
╷
│ Error: Incompatible provider version
│
│ Provider registry.terraform.io/aztfmod/azurecaf v1.2.6 does not have a package available for your current platform, darwin_arm64.
│
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of this provider may have different platforms supported.
```
##### **Suggest a Fix**

We need to generate the terraform scripts with a higher version of the provider, I tried to do this but found that even if the `azurecaf` project supports already arm64 on version 1.2.8 we need to wait until they publish the ARM64 azurecaf provider binaries to fix it. https://github.com/aztfmod/terraform-provider-azurecaf/issues/126

##### **Browsers and Operating System**

Mac M1
macOS Monterrey 12.0.1

**Comment by arnaudlh** [comment]
Friendly ping from CAF team, this should help, let us know: https://github.com/aztfmod/terraform-provider-azurecaf/releases/tag/v1.2.9

**Comment by jdubois** [comment]
Thanks! Let me upgrade to this new version (was this released 30 minutes ago for real????).
I unfortunately can't test, as I don't have one of those new Macs, so @iemejia I'll ping you when it's ready so you can have a try.

**Comment by iemejia** [comment]
Wow I cannot go take lunch before you all fix this. Amazing!
I confirm terraform init works now on Mac M1 (with latest master)! Nice!

@jdubois You have to upgrade de nubesgen.com site so this fix gets out for everyone still.

**Comment by jdubois** [comment]
Thank you @iemejia ! I need several days before doing a new release, we're a bit stuck with the addition of VNet, which is super complicated.
