### ISSUE TITLE
Bicep support over Terraform

### ISSUE THREAD

**Issue by spboyer** [microsoft/NubesGen#22]
Why not using bicep?

**Comment by imod** [comment]
@ernani I created a first draft to support pulumi #117

**Comment by jdubois** [comment]
It is now possible since #157 !
All we need to have is templates in the src/main/resources/nubesgen/bicep directory. @cmaneu is working on those, but any help is of course much welcome.
I'm closing this, as now we'll need to have more specific tickets, like "add MySQL support for Bicep".
