### ISSUE TITLE
KeyVault and Blob storage with VNET integration fail

### ISSUE THREAD

**Issue by felipmiguel** [microsoft/NubesGen#225]
##### **Overview of the issue**
Terraform scripts fail for vnet integration that use storage or key vault.
The reasons for the failures are that some resources are not created thru Azure Resource Management APIs, they are created accessing the resource itself. As the access is limited to a VNET the client executing the script cannot access the resource.
For instance, there are secrets to be created in KeyVault and containers created in Azure Storage. Both resources require access to KeyVault and Azure Storage.

##### **Suggest a Fix**

To fix this issue it is possible to allow the access to the IP of the machine executing the script.

##### **NubesGen Version(s)**

0.7

**Comment by cmaneu** [comment]
I think this one is closed by #228, do you confirm @felipmiguel?

**Comment by felipmiguel** [comment]
Yes, that is correct.

De: Christopher MANEU ***@***.***>
Enviat: dijous, 23 de desembre de 2021 15:42
Per a: microsoft/NubesGen ***@***.***>
A/c: Felip Miguel Puig ***@***.***>; Mention ***@***.***>
Tema: Re: [microsoft/NubesGen] KeyVault and Blob storage with VNET integration fail (Issue #225)


I think this one is closed by #228<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2FNubesGen%2Fpull%2F228&data=04%7C01%7Cfmiguel%40microsoft.com%7C7b72d3ee532042cd6cbf08d9c6225c75%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637758673193877483%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=7mZrFd9nSXF4q797ScE6gfptpNZCbdMnNIEEgQJy66o%3D&reserved=0>, do you confirm @felipmiguel<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ffelipmiguel&data=04%7C01%7Cfmiguel%40microsoft.com%7C7b72d3ee532042cd6cbf08d9c6225c75%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637758673193877483%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=%2Bvt7zZNhQL4fI16pSyheubDPH19PuYw9evVvj78T250%3D&reserved=0>?

-
