### ISSUE TITLE
Add .NET projects detection

### ISSUE THREAD

**Issue by cmaneu** [microsoft/NubesGen#247]
### Azure SQL
- `Microsoft.Data.SqlClient` 
- `System.Data.SqlClient` 

### PostgresSQL
- `Npgsql` 

### MySQL
- `MySql.data` 
- `MySqlConnector` 

### Application Insights
- `Microsoft.ApplicationInsights` 
### Key Vault
- `Azure.Security.KeyVault`

### Storage Account
- `Azure.Storage.Blobs`

### Redis Cache
- `StackExchange.Redis`
- `Microsoft.Extensions.Caching.Redis`

### MongoDB
- `MongoDB.Driver`

**Comment by jdubois** [comment]
@cmaneu I refactored the code and added this class https://github.com/microsoft/NubesGen/blob/main/cli/src/main/java/io/github/nubesgen/cli/subcommand/scan/DotNetScanner.java to help you (it's copied from the NodeJS scanner, so you need to modify the methods content)

**Comment by jdubois** [comment]
@cmaneu to test this:
- "./mvnw package" in the CLI project to generate the JAR file
- Copy the final JAR file in the "target" repo to an existing project
- Scan the local project: "java -jar nubesgen-cli-0.0.3-SNAPSHOT.jar scan"
