### ISSUE TITLE
Add AKS support

### ISSUE THREAD

**Issue by felipmiguel** [microsoft/NubesGen#277]
Add AKS as new Application type.

Generate the infrastructure to deploy application on AKS. AKS allows many options for some of the components, for instance the registry or the ingress controller. For first version everything on Azure services:
- [ ] Deploy registry. Azure container registry
- [ ] Deploy a VNET
- [ ] Deploy Application Gateway
- [ ] Deploy AKS
- [ ] Deploy AGIC as ingress controller

**Comment by jdubois** [comment]
Closing as this a duplicate from #106 -> @felipmiguel I'll migrate the list there and assign you there
