### ISSUE TITLE
[BUG] CLI on Windows indicates GitHub CLI is not installed, but it is present

### ISSUE THREAD

**Issue by timheuer** [microsoft/NubesGen#417]
**Describe the bug**
The CLI says github CLI is not installed but it is
![image](https://user-images.githubusercontent.com/4821/229629618-c326b336-6230-42ef-bc3c-e59b55d9519e.png)

**Comment by jdubois** [comment]
Oh I'm testing with `gh version` and not `gh --version`, maybe this is specific to Windows? @cmaneu can you reproduce this on your Windows machine?

**Comment by jdubois** [comment]
@timheuer we can't reproduce with @cmaneu , as the doc only mentions `gh --version` I'm going to migrate to this, but I'm not sure it will fix your issue.

**Comment by jdubois** [comment]
We just released a new version that hopefully fixes the bug, but as we can't reproduce I'm not 100% sure. @timheuer your feedback is very welcome here!
