### ISSUE TITLE
Improve terraform state storage account name

### ISSUE THREAD

**Issue by cmaneu** [microsoft/NubesGen#43]
After few usages, I ended up having several storage accounts "for nothing" (I already deleted like 4 of them before this screenshot). And it was very difficult to tie-them back to their project.

![image](https://user-images.githubusercontent.com/790974/110661422-d8743680-81c4-11eb-91d2-24e179e6f35e.png)

I think we should improve the automatic naming we're doing here.

**Comment by bhummerstone** [comment]
If it is about tying it back to a project/application, you could tag the resources with a user-supplied project name?

**Comment by jdubois** [comment]
@bhummerstone oh that's an awesome idea!!!!!

**Comment by jdubois** [comment]
I'm doing this the other way around: we can't know the application name when we run the GitOps script (as it is run before), but I'm adding a tag in the Application resource group to find the storage account easily.
